version: "3.9"
services: 
  influxdb:
    image: influxdb:2.6.1
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=demouser
      - DOCKER_INFLUXDB_INIT_PASSWORD=demouser
      - DOCKER_INFLUXDB_INIT_ORG=influxdb 
      - DOCKER_INFLUXDB_INIT_BUCKET=edge
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=edge
      - DOCKER_INFLUXDB_INIT_RETENTION=1d